// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaIntegralDeportivo.Api.Data;

#nullable disable

namespace SistemaIntegralDeportivo.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816173223_ProductosConFotosYDescripcion")]
    partial class ProductosConFotosYDescripcion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("OrdenInscripcionRanking");

            modelBuilder.HasSequence<int>("OrdenInscripcionRankingDobles");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Alumno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActualizadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Arancel")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ConsentimientoDatos")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ConsentimientoDatosEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ConsentimientoWhatsapp")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ConsentimientoWhatsappEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dni")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EnEsperaDesde")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EsMenor")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProfesorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SedeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TutorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SedeId");

                    b.HasIndex("TutorId");

                    b.HasIndex("TenantId", "Dni")
                        .IsUnique();

                    b.HasIndex("TenantId", "Estado");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.AlumnoHorario", b =>
                {
                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HorarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AlumnoId", "HorarioId");

                    b.HasIndex("HorarioId");

                    b.ToTable("AlumnoHorarios");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Bloqueo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CanchaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dia")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Motivo")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CanchaId");

                    b.HasIndex("TenantId");

                    b.ToTable("Bloqueos");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Cancha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SedeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SedeId", "Nombre")
                        .IsUnique();

                    b.ToTable("Canchas");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("MedioPago")
                        .HasColumnType("text");

                    b.Property<decimal>("Monto")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime?>("PagadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PagoInformadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TurnoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("TurnoId", "AlumnoId")
                        .IsUnique();

                    b.HasIndex("TenantId", "AlumnoId", "Fecha");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.ClaseSuelta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CanchaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CargoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime?>("ResueltoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SedeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TurnoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("CanchaId");

                    b.HasIndex("CargoId");

                    b.HasIndex("SedeId");

                    b.HasIndex("TurnoId");

                    b.HasIndex("TenantId", "Estado");

                    b.ToTable("ClasesSueltas");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Encordado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CuerdaHorizontal")
                        .HasColumnType("text");

                    b.Property<string>("CuerdaVertical")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<Guid>("RaquetaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TensionHorizontal")
                        .HasColumnType("text");

                    b.Property<string>("TensionVertical")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("RaquetaId", "Fecha");

                    b.ToTable("Encordados");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.FotoPerfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<Guid>("PerfilProfesorId")
                        .HasColumnType("uuid");

                    b.Property<string>("PieDeFoto")
                        .HasColumnType("text");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PerfilProfesorId");

                    b.ToTable("FotosPerfil");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.FotoServicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ServicioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ServicioId");

                    b.ToTable("FotosServicio");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.HitoTrayectoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<string>("Detalle")
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<Guid>("PerfilProfesorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PerfilProfesorId");

                    b.ToTable("HitosTrayectoria");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Horario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CanchaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CupoMaximo")
                        .HasColumnType("integer");

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProfesorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ValorHoraProfe")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("CanchaId", "Dia");

                    b.HasIndex("TenantId", "Activo");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.JuegoDoblesPendiente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AceptadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreadoPorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinalizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("GanoParejaA")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Jugador1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Jugador2Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("PuntosGanadores")
                        .HasColumnType("integer");

                    b.Property<int?>("PuntosPerdedores")
                        .HasColumnType("integer");

                    b.Property<Guid>("Rival1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Rival2Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("JuegosDoblesPendientes");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.JuegoPendiente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AceptadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreadoPorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinalizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GanadorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Jugador1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Jugador2Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JugadorMayorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JugadorMenorId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PuntosGanador")
                        .HasColumnType("integer");

                    b.Property<int?>("PuntosPerdedor")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JugadorMenorId", "JugadorMayorId")
                        .IsUnique();

                    b.ToTable("JuegosPendientes");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.JuegoRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreadoPorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("JuegoDoblesPendienteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("JuegoPendienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("RespuestaAdmin")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResueltoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResueltoPorUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JuegoPendienteId", "JuegoDoblesPendienteId", "Estado");

                    b.ToTable("JuegosRevision");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.JugadorRanking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<int?>("CfProvisional")
                        .HasColumnType("integer");

                    b.Property<string>("CiudadResidencia")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaMejorPuesto")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InscriptoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Licencia")
                        .HasColumnType("text");

                    b.Property<string>("Mano")
                        .HasColumnType("text");

                    b.Property<int?>("MejorPuestoHistorico")
                        .HasColumnType("integer");

                    b.Property<int>("OrdenInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"OrdenInscripcionRanking\"')");

                    b.Property<string>("Pais")
                        .HasColumnType("text");

                    b.Property<bool>("PerfilPublico")
                        .HasColumnType("boolean");

                    b.Property<bool>("PermiteContacto")
                        .HasColumnType("boolean");

                    b.Property<int?>("PosicionProvisional")
                        .HasColumnType("integer");

                    b.Property<string>("Provincia")
                        .HasColumnType("text");

                    b.Property<int>("PuntosProvisionales")
                        .HasColumnType("integer");

                    b.Property<string>("RangoProvisional")
                        .HasColumnType("text");

                    b.Property<string>("Reves")
                        .HasColumnType("text");

                    b.Property<string>("Sexo")
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PuntosProvisionales");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("JugadoresRanking");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.JugadorRankingDobles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("CfProvisional")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaMejorPuesto")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InscriptoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JugadorRankingId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MejorPuestoHistorico")
                        .HasColumnType("integer");

                    b.Property<int>("OrdenInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"OrdenInscripcionRankingDobles\"')");

                    b.Property<int?>("PosicionProvisional")
                        .HasColumnType("integer");

                    b.Property<int>("PuntosProvisionales")
                        .HasColumnType("integer");

                    b.Property<string>("RangoProvisional")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JugadorRankingId")
                        .IsUnique();

                    b.HasIndex("PuntosProvisionales");

                    b.ToTable("JugadoresRankingDobles");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.MembresiaTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("PuedeCobrar")
                        .HasColumnType("boolean");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SedeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ValorHora")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("SedeId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique();

                    b.ToTable("MembresiasTenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.NotaAlumno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Compartida")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("TenantId");

                    b.ToTable("NotasAlumno");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Noticia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Importante")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("VenceEl")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Noticias");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Notificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadaEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DestinatarioUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EntidadId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DestinatarioUserId", "Leida");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.PagoEmpleado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MedioPago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime>("PagadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UserId", "Anio", "Mes")
                        .IsUnique();

                    b.ToTable("PagosEmpleado");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CargoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PedidoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ResueltoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("CargoId");

                    b.HasIndex("TenantId", "Estado");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.PedidoLinea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("NombreServicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nota")
                        .HasColumnType("text");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("ServicioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ServicioId");

                    b.ToTable("PedidoLineas");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.PerfilProfesor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActualizadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AvatarRuta")
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("Especialidades")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("PortadaRuta")
                        .HasColumnType("text");

                    b.Property<string>("PortadaUrl")
                        .HasColumnType("text");

                    b.Property<bool>("Publicado")
                        .HasColumnType("boolean");

                    b.Property<string>("Subtitulo")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titular")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Publicado");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique();

                    b.ToTable("PerfilesProfesor");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Publicidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Enlace")
                        .HasColumnType("text");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Publicidades");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.PuntosMovimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JugadorRankingId")
                        .HasColumnType("uuid");

                    b.Property<int>("Puntos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JugadorRankingId", "Fecha");

                    b.ToTable("PuntosMovimientos");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.PuntosMovimientoDobles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JugadorRankingDoblesId")
                        .HasColumnType("uuid");

                    b.Property<int>("Puntos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JugadorRankingDoblesId", "Fecha");

                    b.ToTable("PuntosMovimientosDobles");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.RankingSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cf")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCorte")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JugadorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Posicion")
                        .HasColumnType("integer");

                    b.Property<int>("Puntos")
                        .HasColumnType("integer");

                    b.Property<string>("Rango")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScopeValor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Modalidad", "Scope", "ScopeValor", "FechaCorte");

                    b.ToTable("RankingSnapshots");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Raqueta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("TenantId");

                    b.ToTable("Raquetas");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Sede", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Nombre")
                        .IsUnique();

                    b.ToTable("Sedes");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Servicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Solicitud", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mensaje")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResueltoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Estado");

                    b.HasIndex("UserId", "TenantId")
                        .IsUnique()
                        .HasFilter("\"Estado\" = 'Pendiente'");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.SolicitudCupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("HorarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResueltoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("HorarioId");

                    b.HasIndex("TenantId", "Estado");

                    b.ToTable("SolicitudesCupo");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.SolicitudHorario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CanchaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<Guid?>("HorarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResueltoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SedeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("CanchaId");

                    b.HasIndex("HorarioId");

                    b.HasIndex("SedeId");

                    b.HasIndex("TenantId", "Estado");

                    b.ToTable("SolicitudesHorario");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AliasCbu")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DirectorDaClases")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Subdominio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitularPago")
                        .HasColumnType("text");

                    b.Property<decimal?>("ValorClaseIndividual")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal?>("ValorHoraGrupal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("Subdominio")
                        .IsUnique();

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreadoEl = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DirectorDaClases = true,
                            Estado = "Activo",
                            Nombre = "Club Demo",
                            Subdominio = "demo",
                            Tipo = "Profesor"
                        });
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Turno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CanceladoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CanceladoMotivo")
                        .HasColumnType("text");

                    b.Property<string>("CanceladoPor")
                        .HasColumnType("text");

                    b.Property<Guid>("CanchaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<Guid?>("HorarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProfesorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CanchaId");

                    b.HasIndex("HorarioId", "Fecha")
                        .IsUnique();

                    b.HasIndex("TenantId", "Fecha");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.TurnoParticipante", b =>
                {
                    b.Property<Guid>("TurnoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<string>("CancelacionMotivo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CanceloEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Presente")
                        .HasColumnType("boolean");

                    b.HasKey("TurnoId", "AlumnoId");

                    b.HasIndex("AlumnoId");

                    b.ToTable("TurnoParticipantes");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Tutor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Relacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Dni")
                        .IsUnique();

                    b.ToTable("Tutores");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Categoria")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DebeCambiarPassword")
                        .HasColumnType("boolean");

                    b.Property<string>("Dni")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsAdminPlataforma")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Alumno", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Sede", "Sede")
                        .WithMany()
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany("Alumnos")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tutor", "Tutor")
                        .WithMany("Alumnos")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Sede");

                    b.Navigation("Tenant");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.AlumnoHorario", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Horario", "Horario")
                        .WithMany("Alumnos")
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Horario");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Bloqueo", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Cancha", "Cancha")
                        .WithMany()
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Cancha", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Sede", "Sede")
                        .WithMany("Canchas")
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Cargo", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Turno", "Turno")
                        .WithMany()
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Alumno");

                    b.Navigation("Tenant");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.ClaseSuelta", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Cancha", "Cancha")
                        .WithMany()
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Sede", "Sede")
                        .WithMany()
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Turno", "Turno")
                        .WithMany()
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Alumno");

                    b.Navigation("Cancha");

                    b.Navigation("Cargo");

                    b.Navigation("Sede");

                    b.Navigation("Tenant");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Encordado", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Raqueta", "Raqueta")
                        .WithMany("Encordados")
                        .HasForeignKey("RaquetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Raqueta");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.FotoPerfil", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.PerfilProfesor", "Perfil")
                        .WithMany("Fotos")
                        .HasForeignKey("PerfilProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.FotoServicio", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Servicio", "Servicio")
                        .WithMany("Fotos")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.HitoTrayectoria", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.PerfilProfesor", "Perfil")
                        .WithMany("Hitos")
                        .HasForeignKey("PerfilProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Horario", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Cancha", "Cancha")
                        .WithMany("Horarios")
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.MembresiaTenant", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Sede", "Sede")
                        .WithMany()
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sede");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.NotaAlumno", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Noticia", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.PagoEmpleado", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Pedido", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Cargo");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.PedidoLinea", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Pedido", "Pedido")
                        .WithMany("Lineas")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.PerfilProfesor", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Publicidad", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Raqueta", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Alumno", "Alumno")
                        .WithMany("Raquetas")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Sede", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Servicio", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Solicitud", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.SolicitudCupo", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Horario", "Horario")
                        .WithMany()
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Horario");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.SolicitudHorario", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Cancha", "Cancha")
                        .WithMany()
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Horario", "Horario")
                        .WithMany()
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Sede", "Sede")
                        .WithMany()
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Cancha");

                    b.Navigation("Horario");

                    b.Navigation("Sede");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Turno", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Cancha", "Cancha")
                        .WithMany()
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Horario", "Horario")
                        .WithMany("Turnos")
                        .HasForeignKey("HorarioId");

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("Horario");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.TurnoParticipante", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Turno", "Turno")
                        .WithMany("Participantes")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Tutor", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany("Tutores")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Alumno", b =>
                {
                    b.Navigation("Raquetas");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Cancha", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Horario", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Pedido", b =>
                {
                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.PerfilProfesor", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("Hitos");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Raqueta", b =>
                {
                    b.Navigation("Encordados");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Sede", b =>
                {
                    b.Navigation("Canchas");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Servicio", b =>
                {
                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Tenant", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("Tutores");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Turno", b =>
                {
                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Tutor", b =>
                {
                    b.Navigation("Alumnos");
                });
#pragma warning restore 612, 618
        }
    }
}
