// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaIntegralDeportivo.Api.Data;

#nullable disable

namespace SistemaIntegralDeportivo.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Alumno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActualizadoEl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Arancel")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConsentimientoDatos")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ConsentimientoDatosEl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConsentimientoWhatsapp")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ConsentimientoWhatsappEl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TutorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.HasIndex("TenantId", "Dni")
                        .IsUnique();

                    b.HasIndex("TenantId", "Estado");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.AlumnoGrupo", b =>
                {
                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("TEXT");

                    b.HasKey("AlumnoId", "GrupoId");

                    b.HasIndex("GrupoId");

                    b.ToTable("AlumnoGrupos");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Grupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CupoMaximo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Activo");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subdominio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Subdominio")
                        .IsUnique();

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Activo = true,
                            CreadoEl = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Club Demo",
                            Subdominio = "demo",
                            Tipo = "Profesor"
                        });
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Tutor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Relacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Dni")
                        .IsUnique();

                    b.ToTable("Tutores");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Alumno", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany("Alumnos")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tutor", "Tutor")
                        .WithMany("Alumnos")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Tenant");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.AlumnoGrupo", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Alumno", "Alumno")
                        .WithMany("Grupos")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Grupo", "Grupo")
                        .WithMany("Alumnos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Grupo", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany("Grupos")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Tutor", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany("Tutores")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Alumno", b =>
                {
                    b.Navigation("Grupos");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Grupo", b =>
                {
                    b.Navigation("Alumnos");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Tenant", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("Grupos");

                    b.Navigation("Tutores");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Tutor", b =>
                {
                    b.Navigation("Alumnos");
                });
#pragma warning restore 612, 618
        }
    }
}
