// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaIntegralDeportivo.Api.Data;

#nullable disable

namespace SistemaIntegralDeportivo.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Alumno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActualizadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Arancel")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ConsentimientoDatos")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ConsentimientoDatosEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ConsentimientoWhatsapp")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ConsentimientoWhatsappEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProfesorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SedeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TutorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SedeId");

                    b.HasIndex("TutorId");

                    b.HasIndex("TenantId", "Dni")
                        .IsUnique();

                    b.HasIndex("TenantId", "Estado");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.AlumnoGrupo", b =>
                {
                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AlumnoId", "GrupoId");

                    b.HasIndex("GrupoId");

                    b.ToTable("AlumnoGrupos");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Aviso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("VenceEl")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Avisos");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Bloqueo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CanchaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dia")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Motivo")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CanchaId");

                    b.HasIndex("TenantId");

                    b.ToTable("Bloqueos");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Cancha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SedeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SedeId", "Nombre")
                        .IsUnique();

                    b.ToTable("Canchas");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("MedioPago")
                        .HasColumnType("text");

                    b.Property<decimal>("Monto")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime?>("PagadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PagoInformadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TurnoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("TurnoId", "AlumnoId")
                        .IsUnique();

                    b.HasIndex("TenantId", "AlumnoId", "Fecha");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.ClaseSuelta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CanchaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CargoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime?>("ResueltoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SedeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TurnoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("CanchaId");

                    b.HasIndex("CargoId");

                    b.HasIndex("SedeId");

                    b.HasIndex("TurnoId");

                    b.HasIndex("TenantId", "Estado");

                    b.ToTable("ClasesSueltas");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Grupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Categoria")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CupoMaximo")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProfesorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Activo");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Horario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CanchaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<Guid?>("GrupoId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<Guid?>("ProfesorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("GrupoId");

                    b.HasIndex("CanchaId", "Dia");

                    b.HasIndex("TenantId", "Activo");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.MembresiaTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique();

                    b.ToTable("MembresiasTenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.NotaAlumno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Compartida")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("TenantId");

                    b.ToTable("NotasAlumno");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CargoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreServicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PedidoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Precio")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime?>("ResueltoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ServicioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("CargoId");

                    b.HasIndex("ServicioId");

                    b.HasIndex("TenantId", "Estado");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Publicidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Enlace")
                        .HasColumnType("text");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Publicidades");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Raqueta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarcaEncordado")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tension")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("TenantId");

                    b.ToTable("Raquetas");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Sede", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Nombre")
                        .IsUnique();

                    b.ToTable("Sedes");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Servicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Solicitud", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mensaje")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResueltoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Estado");

                    b.HasIndex("UserId", "TenantId")
                        .IsUnique()
                        .HasFilter("\"Estado\" = 'Pendiente'");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.SolicitudGrupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResueltoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("GrupoId");

                    b.HasIndex("TenantId", "Estado");

                    b.ToTable("SolicitudesGrupo");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.SolicitudHorario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CanchaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<Guid?>("HorarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResueltoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SedeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("CanchaId");

                    b.HasIndex("HorarioId");

                    b.HasIndex("SedeId");

                    b.HasIndex("TenantId", "Estado");

                    b.ToTable("SolicitudesHorario");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AliasCbu")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Subdominio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitularPago")
                        .HasColumnType("text");

                    b.Property<decimal?>("ValorClaseIndividual")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal?>("ValorHoraGrupal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("Subdominio")
                        .IsUnique();

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreadoEl = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = "Activo",
                            Nombre = "Club Demo",
                            Subdominio = "demo",
                            Tipo = "Profesor"
                        });
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Turno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CanceladoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CanceladoMotivo")
                        .HasColumnType("text");

                    b.Property<string>("CanceladoPor")
                        .HasColumnType("text");

                    b.Property<Guid>("CanchaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<Guid?>("HorarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CanchaId");

                    b.HasIndex("HorarioId", "Fecha")
                        .IsUnique();

                    b.HasIndex("TenantId", "Fecha");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.TurnoParticipante", b =>
                {
                    b.Property<Guid>("TurnoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<string>("CancelacionMotivo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CanceloEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Presente")
                        .HasColumnType("boolean");

                    b.HasKey("TurnoId", "AlumnoId");

                    b.HasIndex("AlumnoId");

                    b.ToTable("TurnoParticipantes");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Tutor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Relacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Dni")
                        .IsUnique();

                    b.ToTable("Tutores");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Categoria")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DebeCambiarPassword")
                        .HasColumnType("boolean");

                    b.Property<string>("Dni")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsAdminPlataforma")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Alumno", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Sede", "Sede")
                        .WithMany()
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany("Alumnos")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tutor", "Tutor")
                        .WithMany("Alumnos")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Sede");

                    b.Navigation("Tenant");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.AlumnoGrupo", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Alumno", "Alumno")
                        .WithMany("Grupos")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Grupo", "Grupo")
                        .WithMany("Alumnos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Aviso", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Bloqueo", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Cancha", "Cancha")
                        .WithMany()
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Cancha", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Sede", "Sede")
                        .WithMany("Canchas")
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Cargo", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Turno", "Turno")
                        .WithMany()
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Alumno");

                    b.Navigation("Tenant");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.ClaseSuelta", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Cancha", "Cancha")
                        .WithMany()
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Sede", "Sede")
                        .WithMany()
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Turno", "Turno")
                        .WithMany()
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Alumno");

                    b.Navigation("Cancha");

                    b.Navigation("Cargo");

                    b.Navigation("Sede");

                    b.Navigation("Tenant");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Grupo", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany("Grupos")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Horario", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId");

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Cancha", "Cancha")
                        .WithMany("Horarios")
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId");

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Cancha");

                    b.Navigation("Grupo");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.MembresiaTenant", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.NotaAlumno", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Pedido", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Cargo");

                    b.Navigation("Servicio");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Publicidad", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Raqueta", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Alumno", "Alumno")
                        .WithMany("Raquetas")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Sede", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Servicio", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Solicitud", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.SolicitudGrupo", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Grupo");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.SolicitudHorario", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Cancha", "Cancha")
                        .WithMany()
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Horario", "Horario")
                        .WithMany()
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Sede", "Sede")
                        .WithMany()
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Cancha");

                    b.Navigation("Horario");

                    b.Navigation("Sede");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Turno", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Cancha", "Cancha")
                        .WithMany()
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Horario", "Horario")
                        .WithMany("Turnos")
                        .HasForeignKey("HorarioId");

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("Horario");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.TurnoParticipante", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Turno", "Turno")
                        .WithMany("Participantes")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Tutor", b =>
                {
                    b.HasOne("SistemaIntegralDeportivo.Api.Models.Tenant", "Tenant")
                        .WithMany("Tutores")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Alumno", b =>
                {
                    b.Navigation("Grupos");

                    b.Navigation("Raquetas");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Cancha", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Grupo", b =>
                {
                    b.Navigation("Alumnos");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Horario", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Sede", b =>
                {
                    b.Navigation("Canchas");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Tenant", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("Grupos");

                    b.Navigation("Tutores");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Turno", b =>
                {
                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("SistemaIntegralDeportivo.Api.Models.Tutor", b =>
                {
                    b.Navigation("Alumnos");
                });
#pragma warning restore 612, 618
        }
    }
}
